//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandboxPolicy.Entities
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Insured
    {
        public int InsuredId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string DbaName { get; set; }
        public string InsuredType { get; set; }
        public int PolicyId { get; set; }
        public int TransactionId { get; set; }
    
        public virtual Policy Policy { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
