//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandboxPolicy.Entities
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class PolicyCoverage
    {
        public int PolicyCoverageId { get; set; }
        public string PolicyCoverageName { get; set; }
        public Nullable<decimal> Limit { get; set; }
        public Nullable<decimal> Deductible { get; set; }
        public int PolicyId { get; set; }
        public int TransactionId { get; set; }
    
        public virtual Policy Policy { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
