//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandboxPolicy.Entities
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Policy
    {
        public Policy()
        {
            this.Insured = new HashSet<Insured>();
            this.PolicyCoverage = new HashSet<PolicyCoverage>();
        }
    
        public int PolicyId { get; set; }
        public int Mod { get; set; }
        public string Status { get; set; }
        public string PolicyNumber { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public int TransactionId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Insured> Insured { get; set; }
        public virtual Transaction Transaction { get; set; }
        public virtual ICollection<PolicyCoverage> PolicyCoverage { get; set; }
    }
}
